name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  CI_SYSTEM: GitHub Action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --scan
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_API_KEY }}
      - name: Deploy Artifacts to Github Pages
        run: ./gradlew :gitPublishPush
        if: github.ref == 'refs/heads/master'
        env:
          GRGIT_USER: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
      - name: Deploy Artifacts to GitHub Releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            mywarp-bukkit/build/libs/mywarp-bukkit*-all.jar
            mywarp-bukkit/build/libs/mywarp-bukkit*[0-9].jar
            mywarp-core/build/libs/mywarp-core*[0-9].jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
